yandex:
  home_latitude: 55.57
  home_longitude: 37.66
  work_latitude: 55.71
  work_longitude: 37.64
  interval: 60 # in seconds

mqtt:
  server: 192.168.1.93
  port: 1883
  username: mqtt_user
  password: passw0rd
  prefix: home
